name: flutter_saster
description: "Aklan Emergency Response Network mobile app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  image_picker: ^1.2.2
  url_launcher: ^6.3.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  shared_preferences: ^2.5.3
  flutter_svg: ^2.3.0
  chewie: ^1.14.1
  video_player: ^2.11.1
  sqflite: ^2.4.4
  path: ^1.9.1
  path_provider: ^2.1.6
  connectivity_plus: ^7.3.1
  uuid: ^4.6.0
  sqlite3: ^3.5.2
  flutter_map_vector_tiles: ^2.9.0
  flutter_map_vector_tiles_mbtiles: 1.0.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  sqflite_common_ffi: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/kalibo_barangays.geojson
    - assets/data/ibajay_puroks.geojson
    - assets/images/
    - assets/maps/aklan.mbtiles
    - assets/styles/liberty/style.json
    - assets/styles/liberty/sprite.json
    - assets/styles/liberty/sprite.png
    - assets/styles/liberty/sprite@2x.json
    - assets/styles/liberty/sprite@2x.png


flutter_launcher_icons:
  android: true
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
  ios: false
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 23